name: Lint and test

on:
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: 14

jobs:
  linting-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: actions/checkout@v2
    - uses: cypress-io/github-action@v2
    - env:
      CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
    - run: npm ci
    - run: npm run cypress
    - run: npm run lint
    - run: npm run test
